[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# context.payasaka_dos_before
# Runs before payasaka_before
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "-- context.before calculations"
position = 'before'
payload = '''
local should_return = PTASaka.dos_cardarea.disabled
PTASaka.dos_cardarea.disabled = true
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, payasaka_dos_before = true})
text, disp_text, poker_hands = G.FUNCS.get_poker_hand_info(G.play.cards)
SMODS.displayed_hand = text
'''
match_indent = true
times = 1

# Return cardarea state & Wild Two revert
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "-- TARGET: effects after hand evaluation"
position = 'after'
payload = '''
PTASaka.dos_cardarea.disabled = should_return
G.E_MANAGER:add_event(Event({
	func = function()
		for k, card in ipairs(G.play.cards) do
			if card.payasaka_wild_two then
				card:flip()
				--if card.children.front then
				--	card.children.front = nil
				--end
			end
		end
		return true
	end
}))
'''
match_indent = true
times = 1

# context.payasaka_before
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "-- context.before calculations"
position = 'before'
payload = '''
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, payasaka_before = true})
text, disp_text, poker_hands = G.FUNCS.get_poker_hand_info(G.play.cards)
SMODS.displayed_hand = text
'''
match_indent = true
times = 1

# Allow dynamic changing of hand chips and mult before scoring
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "-- TARGET: effects before scoring starts"
position = 'before'
payload = '''
text,disp_text,poker_hands,_,__ = G.FUNCS.get_poker_hand_info(G.play.cards)
'''
match_indent = true
times = 1

# Add fnnuy card area to calculate contexts
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "-- TARGET: add your own CardAreas for joker evaluation"
position = "after"
payload = '''
t[#t+1] = PTASaka.dos_cardarea
'''
match_indent = true
times = 1

# Change order of playing cards v. jokers when idk is present
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "for _, v in ipairs(SMODS.get_card_areas('playing_cards')) do"
position = "at"
payload = '''
local idk_present = next(SMODS.find_card('j_payasaka_idk'))
for _, v in ipairs(idk_present and {} or SMODS.get_card_areas('playing_cards')) do
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "-- context.final_scoring_step calculations"
position = "before"
payload = '''
for _, v in ipairs(idk_present and SMODS.get_card_areas('playing_cards') or {}) do
	SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, v == G.play and scoring_hand or nil)
    delay(0.3)
end
'''
match_indent = true
times = 1

# Don't show debuff shader until its time
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = "self.children.center:draw_shader('debuff', nil, self.ARGS.send_to_shader)"
position = "at"
payload = '''
if not self.pta_no_show_debuff then self.children.center:draw_shader('debuff', nil, self.ARGS.send_to_shader) end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = "self.children.front:draw_shader('debuff', nil, self.ARGS.send_to_shader)"
position = "at"
payload = '''
if not self.pta_no_show_debuff then self.children.front:draw_shader('debuff', nil, self.ARGS.send_to_shader) end
'''
match_indent = true
times = 1

# Remove retriggers if Aww! No Retriggers is present
# ALL of them
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "if _type == 'joker_retrigger' then"
position = "before"
payload = '''
if PTASaka.stop_you_are_violating_the_law then 
	effect = { fake_repetitions = eval.repetitions or 1 }
	if _type == 'joker_retrigger' then
            effect.retrigger_card = effect_card
            effect.message_card = effect.message_card or effect_card
            effect.retrigger_flag = true
        elseif _type == 'individual_retrigger' then
            effect.retrigger_card = effect_card.object
            effect.message_card = effect.message_card or effect_card.scored_card
        elseif not _type then
            effect.card = effect.card or effect_card
        end
	eval.repetitions = 0
	SMODS.calculate_effect(effect, effect.retrigger_card or effect.card)
	return 
end
'''
match_indent = true
times = 1

# Custom context for drawing additional cards lmao
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "for i=1, hand_space do --draw cards from deckL"
position = "before"
payload = '''
local add = {}
SMODS.calculate_context({payasaka_draw_to_deck = true}, add)
SMODS.trigger_effects(add)
for k, v in ipairs(add) do
	for _k, _v in pairs(v) do
		hand_space = math.min(hand_space + (_v.draw_amount or 0), #G.deck.cards)
	end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''draw_card(G.play,G.discard, it*100/play_count,'down', false, v)'''
position = 'at'
payload = '''
if not G.GAME.payasaka_prelude then
	local add = {}
	SMODS.calculate_context({payasaka_play_to_discard = true, other_card = v, scoring_hand = {v}}, add)
	SMODS.trigger_effects(add)
	local target = G.discard
	for k, v in ipairs(add) do
		for _k, _v in pairs(v) do
			target = _v.target or target
		end
	end
	draw_card(G.play,target, it*100/play_count,'down', false, v)
else
	local target = G.deck
	local add = {}
	SMODS.calculate_context({payasaka_play_to_discard = true, other_card = v, scoring_hand = {v}}, add)
	SMODS.trigger_effects(add)
	for k, v in ipairs(add) do
		for _k, _v in pairs(v) do
			target = _v.target or target
		end
	end
	draw_card(G.play,target, it*100/play_count,'down', false, v)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.hand.highlighted[i].ability.discarded = true'''
position = 'after'
payload = '''
PTASaka.freeze_card(G.hand.highlighted[i], nil, true);
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.E_MANAGER:add_event(Event({
          trigger = 'immediate',
          func = function()
            ease_round(1)'''
position = 'before'
payload = '''
G.GAME.payasaka_blind_override = e.config.ref_table
G.E_MANAGER:add_event(Event({
	trigger = 'immediate',
	func = function()
		local add = {}
		SMODS.calculate_context({payasaka_pre_setting_blind = true, blind = G.GAME.payasaka_blind_override}, add)
		SMODS.trigger_effects(add)
		for k, v in ipairs(add) do
			for _k, _v in pairs(v) do
				G.GAME.payasaka_blind_override = G.P_BLINDS[_v.override] or G.GAME.payasaka_blind_override
			end
		end
		return true
	end
}))
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.GAME.round_resets.blind = e.config.ref_table'''
position = 'at'
payload = '''
G.GAME.round_resets.blind = G.GAME.payasaka_blind_override
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''if G.GAME.round_resets.blind_states.Boss == 'Defeated' then '''
position = 'before'
payload = '''
local add = {}
SMODS.calculate_context({payasaka_cash_out = true}, add)
SMODS.trigger_effects(add)
'''
match_indent = true

# Add custom context to individual debuffed cards
# I don't want to make other mods that add this trigger them twice...
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''else
            if scoring_hand then
                if in_scoring then context.cardarea = G.play else context.cardarea = 'unscored' end
            end
            SMODS.score_card(card, context)
        end'''
position = "after"
payload = '''
if card.debuff then
	if scoring_hand then
		if in_scoring then context.cardarea = G.play else context.cardarea = 'unscored' end
	end

	local reps = { 1 }
    local j = 1
    while j <= #reps do
        if reps[j] ~= 1 then
            local _, eff = next(reps[j])
            while eff.retrigger_flag do 
                SMODS.calculate_effect(eff, eff.card); j = j+1; _, eff = next(reps[j]) 
            end
            SMODS.calculate_effect(eff, eff.card)
            percent = (percent or 0) + (percent_delta or 0.08)
        end

		local effects = {}
		SMODS.calculate_context({payasaka_debuff_individual = true, card = card, cardarea = context.cardarea}, effects)

		local flags = SMODS.trigger_effects(effects, card)
        if reps[j] == 1 and flags.calculated then
            context.repetition = true
            context.card_effects = effects
			context.ignore_debuff = true
			context.other_card = card
            SMODS.calculate_repetitions(card, context, reps)
			context.ignore_debuff = nil
            context.repetition = nil
            context.card_effects = nil
        end
        j = j + (flags.calculated and 1 or #reps)
		context.other_card = nil
	end
end
'''
match_indent = true
times = 1

# Always keep track of added food jokers
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''SMODS.calculate_context({card_added = true, card = self})'''
position = "after"
payload = '''
G.GAME.found_food_jokers = G.GAME.found_food_jokers or {}
G.GAME.found_food_joker_count = G.GAME.found_food_joker_count or 0
if self.config.center.pools and self.config.center.pools["Food"] and not G.GAME.found_food_jokers[self.config.center_key] then
	G.GAME.found_food_jokers[self.config.center_key] = true
	G.GAME.found_food_joker_count = G.GAME.found_food_joker_count + 1
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''SMODS.calculate_context({using_consumeable = true, consumeable = card, area = card.from_area})'''
position = 'before'
payload = '''
if card.ability.eternal then dont_dissolve = true; area = G.consumeables; draw_card(G.play, area, 1, 'up', true, card, nil, mute); end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''-- TARGET: card destroyed'''
position = 'after'
payload = '''
if destroyed then
	context.payasaka_prevent_destroy_card = card
	context.destroy_card = nil
	context.destroying_card = nil
	local flags = SMODS.calculate_context(context)
	context.payasaka_prevent_destroy_card = nil
	if flags.prevent_remove then destroyed = false end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''-- TARGET: main scoring on played cards'''
position = 'after'
payload = '''
--if not Talisman then
	local e_chips = card:get_pta_e_chips()
	if e_chips > 0 then
		ret.playing_card.e_chips = e_chips
	end

	local e_mult = card:get_pta_e_mult()
	if e_mult > 0 then
		ret.playing_card.e_mult = e_mult
	end
--end

local balance = card:get_pta_balance()
if balance > 0 then
	ret.playing_card.pta_balance = balance
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''bonus_chips = bonus_chips ~= 0 and bonus_chips or nil,'''
position = 'after'
payload = '''
bonus_e_chips = (self.ability.perma_e_chips ~= 0 and self.ability.perma_e_chips ~= nil) and (self.ability.perma_e_chips + 1) or nil,
bonus_e_mult = (self.ability.perma_e_mult ~= 0 and self.ability.perma_e_mult ~= nil) and (self.ability.perma_e_mult + 1) or nil,
bonus_balance = (self.ability.perma_balance ~= 0 and self.ability.perma_balance ~= nil) and self.ability.perma_balance or nil,
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if specific_vars and specific_vars.bonus_p_dollars then'''
position = 'before'
payload = '''
if specific_vars and specific_vars.bonus_e_chips then
	localize{type = 'other', key = 'card_extra_e_chips', nodes = desc_nodes, vars = {specific_vars.bonus_e_chips}}
end
if specific_vars and specific_vars.bonus_e_mult then
	localize{type = 'other', key = 'card_extra_e_mult', nodes = desc_nodes, vars = {specific_vars.bonus_e_mult}}
end
if specific_vars and specific_vars.bonus_balance then
	localize{type = 'other', key = 'card_extra_balance', nodes = desc_nodes, vars = {specific_vars.bonus_balance*100}}
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
pattern = '''if specific_vars and specific_vars.bonus_p_dollars then'''
position = 'before'
payload = '''
if specific_vars and specific_vars.bonus_e_chips then
	localize{type = 'other', key = 'card_extra_e_chips', nodes = desc_nodes, vars = {specific_vars.bonus_e_chips}}
end
if specific_vars and specific_vars.bonus_e_mult then
	localize{type = 'other', key = 'card_extra_e_mult', nodes = desc_nodes, vars = {specific_vars.bonus_e_mult}}
end
if specific_vars and specific_vars.bonus_balance then
	localize{type = 'other', key = 'card_extra_balance', nodes = desc_nodes, vars = {specific_vars.bonus_balance*100}}
end
'''
match_indent = true

# Add old version of context.pseudorandom_result here
# As this needs to run BEFORE the jokers to properly work
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''SMODS.post_prob = SMODS.post_prob or {}'''
position = 'before'
payload = '''
SMODS.calculate_context({payasaka_pseudorandom_result = true, result = result, trigger_obj = trigger_obj, numerator = numerator, denominator = denominator, identifier = identifier or seed})
'''
match_indent = true

# Allow Haru Urara to allow held in hand repetitions
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''SMODS.calculate_repetitions(card, context, reps)'''
position = "after"
payload = '''
if context.cardarea == "unscored" and context.payasaka_haru_urara_old_area == G.hand then
	context.cardarea = G.hand
	SMODS.calculate_repetitions(card, context, reps)
	context.cardarea = "unscored"
end
'''
match_indent = true
times = 1

# Allow King Halo + other unscored centric jokers to do individual context triggers on score cards
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''SMODS.calculate_card_areas('jokers', context, effects, { main_scoring = true })'''
position = "after"
payload = '''
if context.cardarea == G.play and SMODS.has_enhancement(card, "m_payasaka_score") then
	context.cardarea = "unscored"
	SMODS.calculate_card_areas('jokers', context, effects, { main_scoring = true })
	context.cardarea = G.play
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''SMODS.calculate_card_areas('individual', context, effects, { main_scoring = true })'''
position = "after"
payload = '''
if context.cardarea == G.play and SMODS.has_enhancement(card, "m_payasaka_score") then
	context.cardarea = "unscored"
	SMODS.calculate_card_areas('individual', context, effects, { main_scoring = true })
	context.cardarea = G.play
end
'''
match_indent = true
times = 1

# Same with repetitions
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''SMODS.calculate_repetitions(card, context, reps)'''
position = "after"
payload = '''
if context.cardarea == G.play and SMODS.has_enhancement(card, "m_payasaka_score") then
	context.cardarea = "unscored"
	SMODS.calculate_repetitions(card, context, reps)
	context.cardarea = G.play
end
'''
match_indent = true
times = 1

# STATUSES #

# Statuses should still be active even if debuffed
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if not card:can_calculate(context.ignore_debuff, context.remove_playing_cards) then
        if card.ability.rental then
            local ret = {}
            ret[SMODS.Stickers.rental] = card:calculate_sticker(context, 'rental')
            return ret, {}
        end
        return {}, {}
    end'''
position = 'at'
payload = '''
if not card:can_calculate(context.ignore_debuff, context.remove_playing_cards) then
	local ret = {}
	for _,k in ipairs(PTASaka.Status.obj_buffer) do
        local v = PTASaka.Statuses[k]
        local status = card:calculate_status(context, k)
        if status then
            ret[v] = status
        end
    end
	for _,k in ipairs(SMODS.Sticker.obj_buffer) do
        local v = SMODS.Stickers[k]
		if v.payasaka_debuff_calculate then
			local status = card:calculate_sticker(context, k)
			if status then
				ret[v] = status
			end
		end
    end
    if card.ability.rental then
        ret[SMODS.Stickers.rental] = card:calculate_sticker(context, 'rental')
    end
    return ret, {}
end
'''
match_indent = true

# Calculate status effect returns
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''-- TARGET: evaluate your own general effects'''
position = 'after'
payload = '''
for _,k in ipairs(PTASaka.Status.obj_buffer) do
    local v = PTASaka.Statuses[k]
    local status = card:calculate_status(context, k)
    if status then
        ret[v] = status
    end
end
'''
match_indent = true

# Calculate effects
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''for _, k in ipairs(SMODS.Sticker.obj_buffer) do'''
position = 'before'
payload = '''
for _, k in ipairs(PTASaka.Status.obj_buffer) do
    local v = PTASaka.Statuses[k]
    SMODS.calculate_effect_table_key(effect_table, v, card, ret)
end
'''
match_indent = true

# Apply status info_queue
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local sticker = SMODS.Stickers[v]
            if sticker then
                local t = { key = v, set = 'Other' }'''
position = 'before'
payload = '''
local status = PTASaka.Statuses[v]
if status then
    local t = { key = v, set = 'Status' }
    local res = {}
    if status.loc_vars and type(status.loc_vars) == 'function' then
        res = status:loc_vars(info_queue, card) or {}
        t.vars = res.vars or {}
        t.key = res.key or t.key
        t.set = res.set or t.set
    end
    info_queue[#info_queue+1] = t
end
'''
match_indent = true

# Apply status info_queue
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''localize{type = 'other', key = _c.key, nodes = desc_nodes, vars = specific_vars or _c.vars}'''
position = 'after'
payload = '''
elseif _c.set == "Status" then
	localize{type = 'descriptions', set = _c.set, key = _c.key, nodes = desc_nodes, vars = specific_vars or _c.vars}
elseif _c.set == "TagBag" and full_UI_table.name then
	localize{type = 'descriptions', set = _c.set, key = _c.key, nodes = desc_nodes, vars = specific_vars or _c.vars}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''for k, v in pairs(SMODS.Stickers) do'''
position = 'before'
payload = '''
for k, v in pairs(PTASaka.Statuses) do
	G.BADGE_COL[k] = v.badge_colour
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''for k, v in ipairs(SMODS.Sticker.obj_buffer) do'''
position = 'before'
payload = '''
for k, v in ipairs(PTASaka.Status.obj_buffer) do
    if self.ability[v] and not PTASaka.Statuses[v].hide_badge then
        badges[#badges+1] = v
    end
end
'''
match_indent = true