[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# context.payasaka_before
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
elseif e.config.id ~= 'buy_and_use' then
  if c1.ability.consumeable then'''
position = 'at'
payload = '''
elseif e.config.id ~= 'buy_and_use' then
  if c1.ability.set == "DOSCard" then
	PTASaka.dos_cardarea:emplace(c1)
  elseif c1.ability.consumeable then
'''
match_indent = true
times = 1

# Add active state text in CardArea ui box
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''
self.children.area_uibox = UIBox{'''
position = 'before'
payload = '''
card_count = (PTASaka and self == PTASaka.dos_cardarea) and {n=G.UIT.R, config={align = 'cl', padding = 0.03, no_fill = true}, nodes={
    {n=G.UIT.B, config={w = 0.1,h=0.1}},
    {n=G.UIT.R, config={align = 'cl', padding = 0.03, no_fill = true}, nodes = {
      {n=G.UIT.C, config={align = 'cl', minw = 1.2, no_fill = true}, nodes = {
        {n=G.UIT.T, config={ref_table = PTASaka, ref_value = 'dos_enabled_string', scale = 0.3, colour = G.C.WHITE}},
      }},
      {n=G.UIT.B, config={w = 0.2,h=0.1}},
      {n=G.UIT.T, config={ref_table = self.config, ref_value = 'card_count', scale = 0.3, colour = G.C.WHITE}},
      {n=G.UIT.T, config={text = '/', scale = 0.3, colour = G.C.WHITE}},
      {n=G.UIT.T, config={ref_table = self.config, ref_value = 'card_limit', scale = 0.3, colour = G.C.WHITE}},
    }},
    {n=G.UIT.B, config={w = 0.1,h=0.1}}
}} or card_count
'''
match_indent = true
times = 1
