[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add an exception for Snapgraph
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = "elseif card.ability.set == 'Joker' then "
position = 'before'
payload = '''
elseif card.config.center.pta_usable and card.from_area ~= G.shop and card.from_area ~= G.pack_cards then 
	draw_card(G.hand, G.play, 1, 'up', true, card, nil, mute)
	dont_dissolve = true
    delay(0.2)
    PTASaka.use_joker(card, area)
    SMODS.calculate_context({using_consumeable = true, consumeable = card, area = card.from_area})
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''(G.GAME.used_vouchers["v_directors_cut"] and not G.GAME.round_resets.boss_rerolled)) then'''
position = 'at'
payload = '''
(G.GAME.used_vouchers["v_directors_cut"] and not G.GAME.round_resets.boss_rerolled)) and not G.GAME.payasaka_cannot_reroll then
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''-- TARGET: main end_of_round evaluation'''
position = 'before'
payload = '''
if G.GAME.blind_on_deck == 'Boss' and not game_over and G.GAME.payasaka_fucking_hell then
	if #G.consumeables.cards < G.consumeables.config.card_limit then
		local _c = SMODS.add_card { key = 'c_payasaka_gacha', area = G.consumeables }
		_c:juice_up()
	end
end
'''
match_indent = true
times = 1

# Add ahead info_queue if applicable
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
pattern = '''desc_nodes.background_colour = res.background_colour'''
position = 'before'
payload = '''
if card and card.is_ahead and card:is_ahead() then
	info_queue[#info_queue+1] = PTASaka.DescriptionDummies["dd_payasaka_ahead"]
end
'''
match_indent = true

# Add ahead info_queue if applicable
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if first_pass and not (_c.set == 'Edition') and badges then'''
position = 'before'
payload = '''
if card and card.config and card.config.center and (not card.config.center.mod) and card.is_ahead and card:is_ahead() and _c.set ~= "Booster" then
	info_queue[#info_queue+1] = PTASaka.DescriptionDummies["dd_payasaka_ahead"]
end
'''
match_indent = true

# Risk card spawning (unaffected by showman)
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''G.GAME.spectral_rate = G.GAME.spectral_rate or 0'''
position = 'before'
payload = '''
if G.GAME.payasaka_only_risk and area == G.shop_jokers then
	local risk_card = SMODS.create_card { set = "Risk", area = area }
	create_shop_card_ui(risk_card, 'Risk', area)
	return risk_card
end
'''
match_indent = true

# Oh fuck
[[patches]]
[patches.pattern]
target = 'main.lua'
pattern = '''if (love.system.getOS() == 'OS X' ) and (jit.arch == 'arm64' or jit.arch == 'arm') then jit.off() end'''
position = 'before'
payload = '''
-- I am injecting at the very start baybee
pta_amount_of_lua_files_loaded_please_dont_override = 0
local old_require = require
function require(f, ...)
	-- we dont need to load it again, capisce?
	if not package.loaded[f] then
		pta_amount_of_lua_files_loaded_please_dont_override = pta_amount_of_lua_files_loaded_please_dont_override + 1
	end
	return old_require(f, ...)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/loader.lua"]'''
pattern = '''if not chunk then return nil, "Error processing file '" .. path .. "' for mod with ID '" .. mod.id .. "': " .. err end'''
position = 'after'
payload = '''
pta_amount_of_lua_files_loaded_please_dont_override = pta_amount_of_lua_files_loaded_please_dont_override + 1
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''local sell = nil'''
position = 'before'
payload = '''
if (G.payasaka_gacha_pack_extra and (card.area == G.pack_cards or card.area == G.payasaka_gacha_pack_extra)) then
        if G.STATE == G.STATES.SMODS_BOOSTER_OPENED and (SMODS.OPENED_BOOSTER and SMODS.OPENED_BOOSTER.config.center.kind == 'Gacha') then
            return {
                n=G.UIT.ROOT, config = {padding = 0, colour = G.C.CLEAR}, nodes={
                  {n=G.UIT.R, config={ref_table = card, r = 0.08, padding = 0.1, align = "bm", minw = 0.5*card.T.w - 0.15, maxw = 0.9*card.T.w - 0.15, minh = 0.3*card.T.h, hover = true, shadow = true, colour = G.C.UI.BACKGROUND_INACTIVE, one_press = true, button = 'use_card', func = 'can_select_from_gacha'}, nodes={
                    {n=G.UIT.T, config={text = localize('b_select'),colour = G.C.UI.TEXT_LIGHT, scale = 0.45, shadow = true}}
                  }},
              }}
        end
    end
'''
match_indent = true

# Patch Nopeus to remove stupid ahh crash
[[patches]]
[patches.pattern]
target = '''=[SMODS nopeus "Nopeus.lua"]'''
pattern = '''G.pack_cards:remove()'''
position = 'at'
payload = '''
if G.pack_cards then G.pack_cards:remove() end
'''
match_indent = true

# Why are you crashing.
[[patches]]
[patches.pattern]
target = '''cardarea.lua'''
pattern = '''function CardArea:align_cards()'''
position = 'after'
payload = '''
if not self.cards then self.cards = {} end
if not self.children then self.children = {} end
'''
match_indent = true

# Why are you crashing.
[[patches]]
[patches.pattern]
target = '''cardarea.lua'''
pattern = '''function CardArea:draw()'''
position = 'after'
payload = '''
if not self.cards then self.cards = {} end
if not self.children then self.children = {} end
'''
match_indent = true

# Why are you crashing.
[[patches]]
[patches.pattern]
target = '''cardarea.lua'''
pattern = '''function CardArea:update(dt)'''
position = 'after'
payload = '''
if not self.cards then self.cards = {} end
if not self.children then self.children = {} end
'''
match_indent = true

# Friends of Jimbo stuff
[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''if add and not G.GAME.banned_keys[v.key] then '''
position = 'before'
payload = '''
G.GAME.payasaka_modded_rate = G.GAME.payasaka_modded_rate or 0
if not v.mod and G.GAME.payasaka_modded_rate > 0 and pseudorandom('modded') < G.GAME.payasaka_modded_rate then
	add = false
end
'''
match_indent = true

# Desperado
[[patches]]
[patches.pattern]
target = '''game.lua'''
pattern = '''for i = 1, #G.GAME.tags do
                                            G.GAME.tags[i]:apply_to_run({type = 'voucher_add'})
                                        end'''
position = 'before'
payload = '''
if next(SMODS.find_card('j_payasaka_desperado')) and not nosave_shop then
	G.GAME.current_round.used_packs = G.GAME.current_round.used_packs or {}
	local pack = "p_payasaka_risk_"
	local rng = pseudorandom(pseudoseed('payasaka_risk_desperado'..G.GAME.round_resets.ante), 1, 12)
	if rng < 4 then
		pack = pack.."normal_"..tostring(pseudorandom(pseudoseed('desperado_look'), 1, 2))
	elseif rng < 8 then
		pack = pack.."jumbo_1"
	else
		pack = pack.."mega_1"
	end
	G.GAME.current_round.used_packs[#G.GAME.current_round.used_packs+1] = pack
	local card = Card(G.shop_booster.T.x + G.shop_booster.T.w/2,
        G.shop_booster.T.y, G.CARD_W*1.27, G.CARD_H*1.27, G.P_CARDS.empty, G.P_CENTERS[pack], {bypass_discovery_center = true, bypass_discovery_ui = true})
    card.cost = card.cost / 2
	create_shop_card_ui(card, 'Booster', G.shop_booster)
    card.ability.booster_pos = #G.shop_booster.cards
    card:start_materialize()
    G.shop_booster:emplace(card)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/state_events.lua'''
pattern = '''-- TARGET: main end_of_round evaluation'''
position = 'before'
payload = '''
if next(SMODS.find_card('j_payasaka_iroyokia')) and game_over then
	local c = SMODS.find_card('j_payasaka_iroyokia')[1]
	G.GAME.blind.in_blind = true
	card_eval_status_text(c, 'extra', nil, nil, nil, { message = "Nope!" })
	G.FUNCS.draw_from_discard_to_deck()
	G.STATE = G.STATES.DRAW_TO_HAND
	ease_hands_played(G.GAME.round_resets.hands - G.GAME.current_round.hands_left)
	ease_discard(G.GAME.round_resets.discards - G.GAME.current_round.discards_left)
	G.STATE_COMPLETE = false
	return true
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''draw_card(G.deck,G.hand, i*100/hand_space,'up', true)'''
position = 'after'
payload = '''
if G.GAME.payasaka_erratic_ultra then
	local suit = pseudorandom_element(G.GAME.payasaka_erratic_saved_suits, pseudoseed('erratic2')).key
	local rank = pseudorandom_element(G.GAME.payasaka_erratic_saved_ranks, pseudoseed('erratic2')).key
	local _ = SMODS.change_base(G.deck.cards[#G.deck.cards], suit, rank)
end
'''
match_indent = true
