[manifest]
version = "1.0.0"
dump_lua = true
priority = 214748364

[[patches]]
[patches.copy]
target = "main.lua"
position = "prepend"
sources = [
    "lib/qrankloader.lua",
]

[[patches]]
[patches.copy]
target = '=[SMODS _ "src/loader.lua"]'
position = 'prepend'
sources = [
    "lib/qrankloader.lua",
]

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/loader.lua"]'
pattern = "SMODS.get_optional_features()"
position = "after"
payload = '''
NFS.read = q_rankloader.old_nfs_read or NFS.read
'''
match_indent = true 
