[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

# we having lua warnings with this one !!!
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''cover = dollar_UI.parent,'''
position = 'after'
payload = '''
scale = 0.5,
'''
match_indent = true
times = 1

# Handle buying cards that require pyrox
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''local t2 = card.ability.set == 'Voucher' and {'''
position = 'before'
payload = '''
if card.config and card.config.center and card.config.center.pyroxenes then
	t1 = {
		n = G.UIT.ROOT,
		config = { minw = 0.6, align = 'tm', colour = darken(G.C.BLACK, 0.2), shadow = true, r = 0.05, padding = 0.05, minh = 1 },
		nodes = {
			{
				n = G.UIT.R,
				config = { align = "cm", colour = lighten(G.C.BLACK, 0.1), r = 0.1, minw = 1, minh = 0.55, emboss = 0.05, padding = 0.03 },
				nodes = {
					{ n = G.UIT.O, config = { object = DynaText({ string = { { prefix = '¥', ref_table = card.config.center, ref_value = 'pyroxenes' } }, colours = { G.C.BLUE }, shadow = true, silent = true, bump = true, pop_in = 0, scale = 0.5 }) } },
				}
			}
		}
	}
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''if c1.cost ~= 0 then'''
position = 'at'
payload = '''
if c1.config and c1.config.center and c1.config.center.pyroxenes then
	ease_pyrox(-c1.config.center.pyroxenes)
elseif c1.cost ~= 0 then
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.cost > 0 then '''
position = 'at'
payload = '''
if self.config and self.config.center and self.config.center.pyroxenes and not G.GAME.DefineBoosterState then
	ease_pyrox(-self.config.center.pyroxenes)
elseif self.cost > 0 then
'''
match_indent = true
times = 1

# Vanilla
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local num_dollars = config.dollars or 1'''
position = 'after'
payload = '''
local num_pyrox = config.pyroxenes or 0
if not config.dollars and num_pyrox > 0 then
	num_dollars = 0
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local dollar_row = 0'''
position = 'before'
payload = '''
local pyrox_row = 0
if num_pyrox > 60 then
	local dollar_string = localize('$') .. num_pyrox
	G.E_MANAGER:add_event(Event({
		trigger = 'before',
		delay = 0.38,
		func = function()
			G.round_eval:add_child(
				{
					n = G.UIT.R,
					config = { align = "cm", id = 'pyrox_row_' .. (pyrox_row + 1) .. '_' .. config.name },
					nodes = {
						{ n = G.UIT.O, config = { object = DynaText({ string = { '¥' .. num_pyrox }, colours = { G.C.BLUE }, shadow = true, pop_in = 0, scale = 0.65, float = true }) } }
					}
				},
				G.round_eval:get_UIE_by_ID('dollar_' .. config.name))

			play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7)
			play_sound('coin6', 1.3, 0.8)
			return true
		end
	}))
elseif num_pyrox > 0 then
	for i = 1, num_pyrox or 1 do
		G.E_MANAGER:add_event(Event({
			trigger = 'before',
			delay = 0.18 - ((num_pyrox > 20 and 0.13) or (num_pyrox > 9 and 0.1) or 0),
			func = function()
				if i % 30 == 1 then
					G.round_eval:add_child(
						{ n = G.UIT.R, config = { align = "cm", id = 'pyrox_row_' .. (pyrox_row + 1) .. '_' .. config.name }, nodes = {} },
						G.round_eval:get_UIE_by_ID('dollar_' .. config.name))
					pyrox_row = pyrox_row + 1
				end

				local r = { n = G.UIT.T, config = { text = '¥', colour = G.C.BLUE, scale = ((num_pyrox > 20 and 0.28) or (num_pyrox > 9 and 0.43) or 0.58), shadow = true, hover = true, can_collide = false, juice = true } }
				play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7 - (num_pyrox > 20 and 0.2 or 0))

				G.round_eval:add_child(r, G.round_eval:get_UIE_by_ID('pyrox_row_' .. (pyrox_row) .. '_' .. config.name))
				G.VIBRATION = G.VIBRATION + 0.4
				return true
			end
		}))
	end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''elseif config.name == 'hands' then'''
position = 'before'
payload = '''
elseif config.name == 'boss_pyrox_bonus' then
	table.insert(left_text, {n=G.UIT.T, config={text = config.pyroxenes or 0, scale = 0.8*scale, colour = G.C.BLUE, shadow = true, juice = true}})
	table.insert(left_text, {n=G.UIT.O, config={object = DynaText({string = ' '..localize('k_payasaka_pyroxene_bonus')..' ', colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''G.GAME.current_round.dollars = config.dollars'''
position = 'after'
payload = '''
G.GAME.current_round.payasaka_pyroxenes = config.pyroxenes or 0
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''add_round_eval_row({name = 'bottom', dollars = dollars})'''
position = 'at'
payload = '''
local pyroxenes = 0

if (G.GAME.blind and G.GAME.blind.boss) or G.GAME.payasaka_fucking_hell then
	add_round_eval_row({name = 'boss_pyrox_bonus', bonus = true, pyroxenes = 5, pitch = pitch})
	pyroxenes = pyroxenes + 5
	pitch = pitch + 0.06
end

add_round_eval_row({name = 'bottom', dollars = dollars, pyroxenes = pyroxenes})
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''ease_dollars(G.GAME.current_round.dollars)'''
position = 'after'
payload = '''
ease_pyrox(G.GAME.current_round.payasaka_pyroxenes or 0)
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.GAME.previous_round.dollars = G.GAME.dollars'''
position = 'after'
payload = '''
G.GAME.previous_round.payasaka_pyroxenes = G.GAME.payasaka_pyroxenes
'''
match_indent = true
times = 1